import {
  Compass,
  ShieldCheck,
  Gauge,
  CalendarRange,
  ShieldAlert,
  Wallet,
  BadgeCheck,
  Workflow,
  Target,
  Eye,
  MessageSquareWarning,
  MessagesSquare,
  ClipboardList,
  Users,
  TrendingUp,
  FileBarChart,
  Milestone,
  Layers,
  Building2,
  HeartPulse,
  Cpu,
  HardHat,
  Landmark,
  Network,
  Headset,
  PhoneOutgoing,
  PhoneIncoming,
  CalendarCheck,
  Cloud,
  Repeat,
  Database,
  Star,
  ShoppingCart,
  Plane,
  GraduationCap,
  RadioTower,
  Banknote,
  House,
  Mic,
  type LucideIcon,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  compass: Compass,
  shield: ShieldCheck,
  gauge: Gauge,
  calendar: CalendarRange,
  risk: ShieldAlert,
  wallet: Wallet,
  badge: BadgeCheck,
  workflow: Workflow,
  target: Target,
  eye: Eye,
  alert: MessageSquareWarning,
  messages: MessagesSquare,
  clipboard: ClipboardList,
  users: Users,
  trending: TrendingUp,
  report: FileBarChart,
  milestone: Milestone,
  layers: Layers,
  building: Building2,
  health: HeartPulse,
  cpu: Cpu,
  hardhat: HardHat,
  landmark: Landmark,
  network: Network,
  headset: Headset,
  outbound: PhoneOutgoing,
  inbound: PhoneIncoming,
  appointment: CalendarCheck,
  cloud: Cloud,
  repeat: Repeat,
  database: Database,
  star: Star,
  cart: ShoppingCart,
  plane: Plane,
  education: GraduationCap,
  telecom: RadioTower,
  finance: Banknote,
  home: House,
  mic: Mic,
};

export function getIcon(name: string): LucideIcon {
  return icons[name] ?? Compass;
}
